### ISSUE TITLE
Формировать тесты исходя из кодов ответов, описанных в сваггере

### ISSUE THREAD

**Issue by watmash** [ErikNas/swagger-testgen#4]
Формировать тесты исходя из кодов ответов, описанных в сваггере. Пример описания кодов ответов из petstore

```
"responses": {
  "200": {
    "description": "successful operation",
    "content": {
      "application/xml": {
        "schema": {
          "$ref": "#/components/schemas/Order"
        }
      },
      "application/json": {
        "schema": {
          "$ref": "#/components/schemas/Order"
        }
      }
    }
  },
  "400": {
    "description": "Invalid ID supplied"
  },
  "404": {
    "description": "Order not found"
  }
```

**Comment by ErikNas** [comment]
Добавил генерацию тестовых методов для каждого из статус кодов ответа.

Нужно еще:

1. Поправить нейминги, но пока не придумал как
2. Убрать хардкод метода для 400 статуса, либо исключить его из генерации и оставить только хардкод
3. Добавил зачатки описания в аннотацию Description, но нужно еще доработать.
